"""Emit the field table and a fitted calibration as Rust the firmware can build.

Two artefacts, and the split is deliberate. The table is bulk numeric data, so
it goes out as a raw little-endian ``f32`` blob that Rust pulls in with
``include_bytes!`` -- 85 kB of binary rather than 300 kB of source literals,
and it lands in flash exactly as it will be read. Everything else -- grid
metadata, geometry, the fitted calibration -- is small and goes out as
generated Rust constants, where a mismatch is a compile error rather than a
silent misread.

Both come from the same objects the host tooling uses, so the firmware cannot
drift away from what the calibration was fitted against.

    uv run python -m cadmouse.export calibration.json
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from .geometry import COUNTS_PER_MT, MAGNET_DIAMETER, MAGNET_HEIGHT, SENSOR_POS
from .magnet import FieldTable, build_table
from .params import CalibParams

#: Where the firmware expects to find them, relative to the repository root.
DEFAULT_BLOB = Path("crates/cadmouse-model/gen/field_table.bin")
DEFAULT_RUST = Path("crates/cadmouse-model/src/generated.rs")


def write_blob(table: FieldTable, path: Path) -> int:
    """``b_rho`` then ``b_z``, row-major over (rho, z), little-endian f32."""
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = np.concatenate(
        [
            np.ascontiguousarray(table.b_rho, dtype="<f4").ravel(),
            np.ascontiguousarray(table.b_z, dtype="<f4").ravel(),
        ]
    )
    path.write_bytes(payload.tobytes())
    return payload.nbytes


def _f32_rows(values: np.ndarray) -> str:
    return ", ".join(f"{v:.9e}" for v in np.asarray(values).ravel())


def _matrix(name: str, values: np.ndarray, rows: int, cols: int) -> str:
    lines = [f"pub const {name}: [[f32; {cols}]; {rows}] = ["]
    for row in np.asarray(values, dtype=float).reshape(rows, cols):
        lines.append(f"    [{_f32_rows(row)}],")
    lines.append("];")
    return "\n".join(lines)


def write_rust(table: FieldTable, params: CalibParams, blob_bytes: int, path: Path) -> None:
    axes = params.magnet_axes()
    parts = [
        "//! Generated by `cadmouse.export`. Do not edit.",
        "//!",
        "//! Regenerate with:",
        "//!     cd scripts && uv run python -m cadmouse.export calibration.json",
        "//!",
        "//! The field table itself lives in `../gen/field_table.bin`; these are",
        "//! the constants needed to index it and the calibration it was fitted with.",
        "",
        "/// Bytes in `gen/field_table.bin`, checked against the include at compile time.",
        f"pub const TABLE_BYTES: usize = {blob_bytes};",
        "",
        f"pub const N_RHO: usize = {table.n_rho};",
        f"pub const N_Z: usize = {table.n_z};",
        f"pub const RHO0: f32 = {table.rho0:.9e};",
        f"pub const D_RHO: f32 = {table.d_rho:.9e};",
        f"pub const Z0: f32 = {table.z0:.9e};",
        f"pub const D_Z: f32 = {table.d_z:.9e};",
        "",
        "/// Tesla -> raw ADC counts, at the 2x sensitivity the firmware uses.",
        f"pub const TESLA_TO_COUNTS: f32 = {1e3 * COUNTS_PER_MT:.9e};",
        "",
        f"/// Magnet geometry the table was built for: {MAGNET_DIAMETER} x {MAGNET_HEIGHT} mm.",
        f"pub const MAGNET_DIAMETER_MM: f32 = {MAGNET_DIAMETER:.9e};",
        f"pub const MAGNET_HEIGHT_MM: f32 = {MAGNET_HEIGHT:.9e};",
        "",
        "/// Sensor positions in the board frame, millimetres. Held fixed by the",
        "/// calibration: they are pick-and-place coordinates and they break the",
        "/// rigid-body gauge freedom.",
        _matrix("SENSOR_POS", SENSOR_POS, 3, 3),
        "",
        "/// Magnet centres in the knob body frame, millimetres.",
        _matrix("MAGNET_POS", params.magnet_pos, 3, 3),
        "",
        "/// Unit magnetisation directions in the knob body frame. The reversed",
        "/// third magnet is carried by a negative moment, not a flipped axis.",
        _matrix("MAGNET_AXIS", axes, 3, 3),
        "",
        "/// Signed magnetic moments, A*m^2.",
        f"pub const MAGNET_MOMENT: [f32; 3] = [{_f32_rows(params.magnet_moment)}];",
        "",
        "/// Per-sensor offset in counts, and per-axis gain.",
        _matrix("SENSOR_OFFSET", params.sensor_offset, 3, 3),
        _matrix("SENSOR_GAIN", params.sensor_gain, 3, 3),
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(parts))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("calibration", type=Path)
    parser.add_argument("--root", type=Path, default=Path(".."), help="repository root")
    args = parser.parse_args(argv)

    table = build_table()
    params = CalibParams.load(args.calibration)

    blob = args.root / DEFAULT_BLOB
    rust = args.root / DEFAULT_RUST
    written = write_blob(table, blob)
    write_rust(table, params, written, rust)

    print(f"wrote {blob} ({written / 1024:.0f} kB, {table.n_rho}x{table.n_z} grid)")
    print(f"wrote {rust}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
