"""Emit golden vectors so the Rust port can be checked against this package.

    uv run python -m cadmouse.golden data/session1.csv calibration.json

The Rust in `crates/cadmouse-model` and `crates/iekf` is a hand port of
`model.py` and `filter.py`. A port is only a port for as long as somebody
checks, and "it looks about right on the board" is not a check -- the failure
mode that matters is a small systematic disagreement, not a crash.

Three things go out, and each isolates a different possible mistake:

* **Forward vectors** -- poses in, counts out. Catches the measurement model:
  geometry, the field table, the bicubic, the calibration constants.
* **Jacobian vectors** -- the vector convention, so a missing right Jacobian of
  SO(3) shows up here rather than as a filter that mysteriously limps.
* **A filter trajectory** -- real recorded frames through the IEKF, with the
  initial pose supplied so the test measures the filter and not the
  initialiser (`solve_pose` is deliberately not ported; the firmware starts
  from its measured rest pose instead).

Written as a Rust source file rather than JSON because the consuming test is
`no_std`-shaped and a parser would be a second thing that can be wrong.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from .dataset import HELDOUT_SEGMENT, load_session
from .filter import FilterConfig, IteratedEkf
from .magnet import build_table
from .model import MEAS_DIM, POSE_DIM, forward, forward_and_jac_vector, solve_pose
from .params import DEFAULT_CALIBRATION, CalibParams

DEFAULT_OUT = Path("crates/cadmouse-model/tests/data/golden_data.rs")

#: Poses to tabulate, spanning the envelope the mechanism actually reaches
#: (about +-1.2 mm and +-4 degrees, measured by filtering the recorded free
#: motion). Includes the neutral pose, which is where the device spends most of
#: its life and where a sign error is least visible.
N_POSES = 24

#: Frames of recorded motion to push through the filter. Long enough that the
#: covariance has settled and any per-step drift between the two
#: implementations has had time to accumulate into something visible.
N_FRAMES = 400


def _poses(rng: np.random.Generator) -> np.ndarray:
    poses = np.zeros((N_POSES, POSE_DIM))
    poses[1:, :3] = rng.uniform(-1.2, 1.2, size=(N_POSES - 1, 3))
    poses[1:, 3:] = rng.uniform(-0.07, 0.07, size=(N_POSES - 1, 3))
    return poses


def _f32_list(values: np.ndarray) -> str:
    return ", ".join(f"{float(v):.9e}" for v in np.asarray(values).ravel())


def _rows(name: str, values: np.ndarray, inner: int, ty: str = "f32") -> str:
    values = np.asarray(values)
    rows = values.reshape(-1, inner)
    lines = [f"pub const {name}: [[{ty}; {inner}]; {len(rows)}] = ["]
    for row in rows:
        if ty == "f32":
            lines.append(f"    [{_f32_list(row)}],")
        else:
            lines.append("    [" + ", ".join(str(int(v)) for v in row) + "],")
    lines.append("];")
    return "\n".join(lines)


def build(session_path: Path, calibration: Path) -> str:
    table = build_table()
    params = CalibParams.load(calibration)
    session = load_session(session_path)
    sigma = session.noise_sigma()
    run = session.by_segment(HELDOUT_SEGMENT)[0]

    rng = np.random.default_rng(20260729)
    poses = _poses(rng)

    counts = np.array([forward(p, params, table) for p in poses])
    jacobians = np.array([forward_and_jac_vector(p, params, table)[1] for p in poses])

    frames = run.counts[:N_FRAMES]
    times = run.t_us[:N_FRAMES]
    initial, converged = solve_pose(frames[0], params, table, sigma=sigma)
    if not converged:
        raise RuntimeError("initial solve_pose did not converge; pick another segment")

    config = FilterConfig()
    ekf = IteratedEkf(params, table, sigma, config, initial_pose=initial)
    trajectory = np.zeros((len(frames), POSE_DIM))
    for k in range(len(frames)):
        dt = (times[k] - times[k - 1]) / 1e6 if k else 0.0
        if dt > 0:
            ekf.predict(dt)
        ekf.update(frames[k])
        trajectory[k] = ekf.x

    dts = np.diff(times, prepend=times[0]) / 1e6

    parts = [
        "// Generated by `cadmouse.golden`. Do not edit.",
        "//",
        "// Regenerate with:",
        "//     cd scripts && uv run python -m cadmouse.golden data/session1.csv calibration.json",
        "//",
        "// Produced by the f64 NumPy implementation in `scripts/cadmouse/`, which",
        "// is the reference the Rust is a port of. See `golden.rs` for the",
        "// tolerances and why they are what they are.",
        "",
        f"pub const N_POSES: usize = {N_POSES};",
        f"pub const N_FRAMES: usize = {len(frames)};",
        f"pub const MEAS_DIM: usize = {MEAS_DIM};",
        f"pub const POSE_DIM: usize = {POSE_DIM};",
        "",
        "/// Poses fed to the model, mm and rad.",
        _rows("POSES", poses, POSE_DIM),
        "",
        "/// `forward(pose)` in counts.",
        _rows("COUNTS", counts, MEAS_DIM),
        "",
        "/// `forward_and_jac_vector(pose)`, flattened row-major (9 x 6) per pose.",
        _rows("JACOBIANS", jacobians, MEAS_DIM * POSE_DIM),
        "",
        "/// Per-channel measurement noise measured from the session's rest blocks.",
        f"pub const SIGMA: [f32; {MEAS_DIM}] = [{_f32_list(sigma)}];",
        "",
        "/// Pose the filter was started from, so the test measures the filter",
        "/// rather than the initialiser.",
        f"pub const INITIAL_POSE: [f32; {POSE_DIM}] = [{_f32_list(initial)}];",
        "",
        "/// Recorded frames, raw counts.",
        _rows("FRAMES", frames, MEAS_DIM, ty="i16"),
        "",
        "/// Seconds between consecutive frames; the first is zero.",
        f"pub const DTS: [f32; {len(dts)}] = [{_f32_list(dts)}];",
        "",
        "/// Pose after each frame, from the Python IEKF.",
        _rows("TRAJECTORY", trajectory, POSE_DIM),
        "",
    ]
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("session", type=Path)
    parser.add_argument(
        "calibration", type=Path, nargs="?", default=DEFAULT_CALIBRATION
    )
    parser.add_argument("--root", type=Path, default=Path(".."), help="repository root")
    args = parser.parse_args(argv)

    text = build(args.session, args.calibration)
    out = args.root / DEFAULT_OUT
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out} ({len(text) / 1024:.0f} kB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
