//! Generated by `cadmouse.export`. Do not edit.
//!
//! Regenerate with:
//!     cd scripts && uv run python -m cadmouse.export calibration.json
//!
//! The field table itself lives in `gen/field_table.bin`; these are the
//! constants needed to index it and the calibration it was fitted with.

/// Bytes in `gen/field_table.bin`, checked against the include at compile time.
pub const TABLE_BYTES: usize = 86856;

pub const N_RHO: usize = 141;
pub const N_Z: usize = 77;
pub const RHO0: f32 = -1.000000000e+00;
pub const D_RHO: f32 = 2.500000000e-01;
pub const Z0: f32 = -2.200000000e+01;
pub const D_Z: f32 = 2.500000000e-01;

/// Tesla -> raw ADC counts, at the 2x sensitivity the firmware uses.
pub const TESLA_TO_COUNTS: f32 = 1.540000000e+04;

/// Magnet geometry the table was built for: 6.0 x 6.0 mm.
pub const MAGNET_DIAMETER_MM: f32 = 6.000000000e+00;
pub const MAGNET_HEIGHT_MM: f32 = 6.000000000e+00;

/// Sensor positions in the board frame, millimetres. Held fixed by the
/// calibration: they are pick-and-place coordinates and they break the
/// rigid-body gauge freedom.
pub const SENSOR_POS: [[f32; 3]; 3] = [
    [0.000000000e+00, -1.651000000e+01, -1.800000000e+01],
    [-1.430000000e+01, 8.260000000e+00, -1.800000000e+01],
    [1.430000000e+01, 8.260000000e+00, -1.800000000e+01],
];

/// Magnet centres in the knob body frame, millimetres.
pub const MAGNET_POS: [[f32; 3]; 3] = [
    [9.128306366e-02, -1.644509770e+01, -9.894961596e+00],
    [-1.436567417e+01, 8.120251621e+00, -9.807506675e+00],
    [1.355695161e+01, 8.570354153e+00, -9.429045649e+00],
];

/// Unit magnetisation directions in the knob body frame. The reversed
/// third magnet is carried by a negative moment, not a flipped axis.
pub const MAGNET_AXIS: [[f32; 3]; 3] = [
    [-1.000843276e-02, -7.069318180e-02, 9.974478960e-01],
    [-6.149464785e-02, 8.507787353e-02, 9.944748180e-01],
    [6.739023449e-03, 1.090457656e-01, 9.940138865e-01],
];

/// Signed magnetic moments, A*m^2.
pub const MAGNET_MOMENT: [f32; 3] = [9.055091541e-02, 8.610544780e-02, -8.278857454e-02];

/// Per-sensor offset in counts, and per-axis gain.
pub const SENSOR_OFFSET: [[f32; 3]; 3] = [
    [1.712091715e+00, 5.870012844e-02, -2.057363190e+01],
    [-7.762873929e-01, 8.553576032e+00, 8.451827772e+00],
    [9.297387250e+00, -2.805001177e+00, 8.916453658e-01],
];
pub const SENSOR_GAIN: [[f32; 3]; 3] = [
    [1.000000000e+00, 1.000000000e+00, 1.000000000e+00],
    [1.000000000e+00, 1.000000000e+00, 1.000000000e+00],
    [1.000000000e+00, 1.000000000e+00, 1.000000000e+00],
];
