//! Generated by `cadmouse.export`. Do not edit.
//!
//! Regenerate with:
//!     cd scripts && uv run python -m cadmouse.export calibrations/calibration.json
//!
//! The field table itself lives in `../gen/field_table.bin`; these are
//! the constants needed to index it and the calibration it was fitted with.

/// Bytes in `gen/field_table.bin`, checked against the include at compile time.
pub const TABLE_BYTES: usize = 99144;

pub const N_RHO: usize = 153;
pub const N_Z: usize = 81;
pub const RHO0: f32 = -1.000000000e+00;
pub const D_RHO: f32 = 2.500000000e-01;
pub const Z0: f32 = -2.200000000e+01;
pub const D_Z: f32 = 2.500000000e-01;

/// Tesla -> raw ADC counts, at the 2x sensitivity the firmware uses.
pub const TESLA_TO_COUNTS: f32 = 1.540000000e+04;

/// Magnet geometry the table was built for: 6.0 x 3.0 mm.
pub const MAGNET_DIAMETER_MM: f32 = 6.000000000e+00;
pub const MAGNET_HEIGHT_MM: f32 = 3.000000000e+00;

/// Sensor positions in the board frame, millimetres. Held fixed by the
/// calibration: they are pick-and-place coordinates and they break the
/// rigid-body gauge freedom.
pub const SENSOR_POS: [[f32; 3]; 3] = [
    [1.010945933e-15, -1.651000000e+01, -1.800000000e+01],
    [-1.429807942e+01, 8.255000000e+00, -1.800000000e+01],
    [1.429807942e+01, 8.255000000e+00, -1.800000000e+01],
];

/// Magnet centres in the knob body frame, millimetres.
pub const MAGNET_POS: [[f32; 3]; 3] = [
    [2.377575996e-02, -1.630816857e+01, -1.168775381e+01],
    [-1.430646874e+01, 8.109651185e+00, -1.095410629e+01],
    [1.361512081e+01, 8.531009142e+00, -1.080254409e+01],
];

/// Unit magnetisation directions in the knob body frame. A reversed
/// magnet is carried by a negative moment, not a flipped axis.
pub const MAGNET_AXIS: [[f32; 3]; 3] = [
    [5.151523266e-02, -5.534567396e-02, 9.971374214e-01],
    [6.387495142e-03, 9.186022128e-03, 9.999374065e-01],
    [5.446059567e-02, 1.246075889e-01, 9.907103473e-01],
];

/// Signed magnetic moments, A*m^2. The sign is measured per device,
/// not assumed; see `cadmouse.calibrate.detect_moment_signs`.
pub const MAGNET_MOMENT: [f32; 3] = [3.790547955e-02, 4.529621480e-02, -4.613573575e-02];

/// Per-sensor offset in counts.
pub const SENSOR_OFFSET: [[f32; 3]; 3] = [
    [4.626072069e+00, 1.625506271e+00, 2.042824027e+01],
    [2.649875146e+00, 2.455931940e+00, 1.762351800e+01],
    [1.674208739e+00, -5.912301817e+00, -1.314982655e+01],
];

/// Symmetric radius of ordinary use: translation in mm, rotation in
/// radians, measured from the recording's `usage` segment. This sets
/// the HID full scale -- see `shaping.rs`. `None` when the session
/// predates the segment.
pub const USAGE_ENVELOPE: Option<(f32, f32)> = Some((1.014670551e+00, 9.395941107e-02));
